[package]
name = "wasm_register_event_callback"
version = "1.0.0"
authors = ["Vladimir Iftodi <Vladimir.Iftodi@gmail.com>"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm_val = "0.3.1"
lazy_static = "1.0.2"